import shutil
from pathlib import Path
from typing import Sequence, List

import suite_file
from defs_file import *

CMD_MK_SUITES = 'mksuite'
CMD_CLEAN  = 'clean'

SUITES_FILE_NAME = 'exactly.suite'


def exit_failure(msg: str):
    print(msg, file=sys.stderr)
    sys.exit(1)


def main():
    if len(sys.argv) < 2:
        exit_failure(usage())
    cmd = sys.argv[1]
    if cmd in ['-h', '--help']:
        print(usage())
    elif cmd == CMD_MK_SUITES:
        _cli_mk_suite(sys.argv[2:])
    elif cmd == CMD_CLEAN:
        _cli_clean(sys.argv[2:])
    else:
        exit_failure('Unknown command: ' + cmd)



def _cli_mk_suite(args: Sequence[str]):
    if len(args) != 3:
        exit_failure('{}: PATTERN CASES-TO-INSTALL-DIR SUITE-PARENT-DIR'.format(CMD_MK_SUITES))
    cases_dir = Path(args[0])
    if not cases_dir.is_dir:
        exit_failure('Not a dir: {}'.format(cases_dir))
    dir_path = Path(args[2])
    if not dir_path.is_dir:
        exit_failure('Not a dir: {}'.format(dir_path))
    _mk_suites(cases_dir, dir_path, args[1])

def _cli_clean(args: Sequence[str]):
    if len(args) != 2:
        exit_failure('{}: PATTERN SUITE-PARENT-DIR'.format(CMD_CLEAN))
    dir_path = Path(args[1])
    if not dir_path.is_dir:
        exit_failure('Not a dir: {}'.format(dir_path))
    _clean(dir_path, args[0])


def _clean(dir_path: Path, suite_env_pattern: str):
    for sc in _suite_configs(dir_path, suite_env_pattern):
        if sc.suite_dir.exists():
            log('Removing suite dir: {}'.format(sc.suite_dir))
            shutil.rmtree(sc.suite_dir)

def _mk_suites(cases_dir: Path, dir_path: Path, suite_env_pattern: str):
    for sc in _suite_configs(dir_path, suite_env_pattern):
        _mk_suite(cases_dir, sc)

def _mk_suite(cases_dir: Path, sc: SuiteConfig):
    if sc.suite_dir.exists():
        log('Skipping suite (dir already exists): {}'.format(sc.suite_dir))
    else:
        log('Creating suite: {}'.format(sc.suite_dir))
        defs = read_defs_file(sc.suite_env_file_parent)
        defs_txt = suite_file.generate(defs)
        # print(defs_txt)
        # sys.exit(1)
        sc.suite_dir.mkdir(parents=True, exist_ok=True)
        write_suite_files_to_dir(cases_dir, sc, defs_txt)

def write_suite_files_to_dir(cases_dir: Path, sc: SuiteConfig, suite_file_txt: str):
    suite_file_path = sc.suite_dir / exactly.SUITE_FILE_NAME
    log('  Creating suite file: {}'.format(suite_file_path))
    suite_file_path.write_text(suite_file_txt)
    for case_file in cases_dir.glob('*'):
        dst = sc.suite_dir / case_file.name
        log('  Installing case: {} -> {}'.format(case_file, dst))
        shutil.copyfile(case_file, dst)






def read_defs_file(p: Path) -> Defs:
    source = p.read_text()
    parser = DefsParser(p, source)
    return parser.parse()


class SuiteConfig:
    def __init__(self, parent: Path, suite_dir: Path, suite_env_file_parent: Path):
        self.parent = parent
        self.suite_dir = suite_dir
        self.suite_env_file_parent = suite_env_file_parent

def _suite_configs(dir_path: Path, suite_env_pattern: str) -> List[SuiteConfig]:
    return [
        SuiteConfig(dir_path, dir_path / suite_env_file.stem, suite_env_file)
        for suite_env_file in dir_path.glob(suite_env_pattern)
    ]


def log(msg):
    print(msg, file=sys.stderr)


def usage() -> str:
    return _USAGE.format()


_USAGE = """\
COMMANDS
  mksuite PATTERN CASES-TO-INSTALL-DIR SUITE-PARENT-DIR
  
    Creates suites corresponding to each found definitions file.
    
    A definitions file is a file matching PATTERN (e.g. '*.def').
    It contains definitions of symbols needed to derive common setup and assertions.
  
  clean  PATTERN SUITE-PARENT-DIR
  
    Removes directories corresponding to suites generated by mksuite."""

if __name__ == '__main__':
    main()
